# For more information: https://laravel.com/docs/sail
version: '3'
services:
    laravel.test:
        build:
            # context: vendor/rmts/scoop-os/docker/8.2
            context: ./vendor/laravel/sail/runtimes/8.2
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.2/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
            - '~/.composer/auth.json:/home/sail/.composer/auth.json:delegated'
            - '~/.ssh:/home/sail/.ssh'
        networks:
            - sail
            - staudacher-proxy
        depends_on:
            - mariadb
            - redis
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.fatbattle.entrypoints=http"
            - "traefik.http.routers.fatbattle.rule=Host(`fatbattle.test`)"
            - "traefik.http.middlewares.fatbattle-https-redirect.redirectscheme.scheme=https"
            - "traefik.http.routers.fatbattle.middlewares=fatbattle-https-redirect"
            - "traefik.http.routers.fatbattle-secure.entrypoints=https"
            - "traefik.http.routers.fatbattle-secure.rule=Host(`fatbattle.test`)"
            - "traefik.http.routers.fatbattle-secure.tls=true"
            - "traefik.http.routers.fatbattle-secure.tls.certresolver=default"
            - "traefik.http.routers.fatbattle-secure.service=fatbattle"
            - "traefik.http.services.fatbattle.loadbalancer.server.port=80"
            - "traefik.docker.network=staudacher-proxy"
    mariadb:
        image: 'mariadb:10.6'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'fatbattle-sail-mariadb:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
    redis:
        image: 'redis:alpine'
        volumes:
            - 'fatbattle-sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s
networks:
    sail:
        driver: bridge
    staudacher-proxy:
        external: true
volumes:
    fatbattle-sail-mariadb:
        driver: local
    fatbattle-sail-redis:
        driver: local
    fatbattle-sail-elasticsearch:
        driver: local
